# Generated by Django 6.0.5 on 2026-05-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imagemproduto",
            options={"ordering": ["ordem"]},
        ),
        migrations.RemoveField(
            model_name="produto",
            name="imagem",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="tag",
        ),
        migrations.AddField(
            model_name="categoria",
            name="icone",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="imagemproduto",
            name="ordem",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="imagemproduto",
            name="principal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="produto",
            name="disponivel",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="produto",
            name="novo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="produto",
            name="preco_original",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
