# Generated by Django 6.0.5 on 2026-05-16 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_favorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='codigo_rastreio',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='rastreio_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
