# Generated by Django 6.0.5 on 2026-05-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='tamanho',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
