# Generated by Django 6.0.5 on 2026-05-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_itempedido_tamanho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('desconto', models.PositiveIntegerField(help_text='Porcentagem de desconto (ex: 10 = 10%)')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cupom',
                'verbose_name_plural': 'Cupons',
                'ordering': ['-criado_em'],
            },
        ),
    ]
