# Generated by Django 6.0.5 on 2026-05-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0009_cupom'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='fora_estoque',
            field=models.BooleanField(default=False),
        ),
    ]
