# Generated by Django 6.0.5 on 2026-05-19 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0012_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='feedbacks/'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='loja.produto'),
        ),
    ]
