# Generated by Django 6.0.5 on 2026-05-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0013_feedback_foto_feedback_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='produto',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='avaliacoes/'),
        ),
    ]
