# Generated by Django 6.0.5 on 2026-05-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0014_remove_feedback_foto_remove_feedback_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
