# Generated by Django 6.0.5 on 2026-05-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0015_alter_produto_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='promocao_ativa',
            field=models.BooleanField(default=False),
        ),
    ]
