# Generated by Django 6.0.5 on 2026-05-29 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0016_produto_promocao_ativa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CupomUsado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usado_em', models.DateTimeField(auto_now_add=True)),
                ('cupom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='loja.cupom')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupons_usados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cupom Usado',
                'verbose_name_plural': 'Cupons Usados',
                'unique_together': {('cupom', 'usuario')},
            },
        ),
    ]
