# Generated by Django 6.0.5 on 2026-06-02 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0017_cupomusado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='mp_payment_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pedido',
            name='mp_preference_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
    ]
